export const PRIMARY_COLOR = '#007bff'; // blue
export const SECONDARY_COLOR = '#6c757d'; // gray
export const SUCCESS_COLOR = '#28a745'; // green
export const DANGER_COLOR = '#dc3545'; // red
export const WARNING_COLOR = '#ffc107'; // yellow
export const INFO_COLOR = '#17a2b8'; // cyan
export const LIGHT_COLOR = '#f8f9fa'; // light gray
export const DARK_COLOR = '#343a40'; // dark gray
export const BACKGROUND_COLOR = '#f5f5f5'; // light gray
export const TEXT_COLOR = '#212529'; // dark gray
export const LINK_COLOR = '#007bff'; // blue
export const BORDER_COLOR = '#dee2e6'; // light gray
export const HOVER_COLOR = '#e2e6ea'; // light gray
export const ACTIVE_COLOR = '#ced4da'; // gray
export const FOCUS_COLOR = '#80bdff'; // light blue
export const ERROR_COLOR = '#dc3545'; // red
export const DISABLED_COLOR = '#6c757d'; // gray
